### ISSUE TITLE
GraphChallenge/StochasticBlockPartition/code/c++ is in python

### ISSUE THREAD

**Issue by maxcuda** [graphchallenge/GraphChallenge#4]
It looks like the C++ code for StochasticBlockPartition has been overwritten by the Python one.

**Comment by edward-kao** [comment]
For the C++ code, please refer to the open source graph-tool library referenced in README. The graph-tool library is implemented in C++ with Python wrappers. The Python code provided in the GraphChallenge/StochasticBlockPartition/code/C++ directory is an example for invoking the graph-tool partition function. Hopefully this answers your question?
