### ISSUE TITLE
Static graph partition- runtime error for the 2018 graph challenge dataset

### ISSUE THREAD

**Issue by Ckins** [graphchallenge/GraphChallenge#8]
In the data set : High Block Overlap and High Block Size Variation, 5000 nodes

The sample code throws out runtime error:

```bash
Traceback (most recent call last):
  File "../partition_baseline_main.py", line 98, in <module>
Number of nodes: 5000
Number of edges: 51157

Merging down blocks from 5000 to 2500
    1, use_sparse_matrix)
  File "/afs/ece.cmu.edu/usr/kching/Desktop/18_static_data/partition_baseline_support.py", line 245, in propose_new_partition
    rand_neighbor = np.random.choice(neighbors[:,0], p=neighbors[:,1]/float(k))
  File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
ValueError: a must be non-empty

```

**Comment by edward-kao** [comment]
Thank you for bringing this to our attention. Could you please let me know which version of Python you are running?

**Comment by Ckins** [comment]
I have tried two platforms with python 2.7
One is Ubuntu 16.04
`Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2`

The other is centos 7
`Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) 
[GCC 7.2.0] on linux2
`

**Comment by edward-kao** [comment]
Turns out the error was caused by a node with no edge (island). I added a few lines of code to take care of such cases. Please do a pull and try again. The issue should be resolved but please let me know if it is not! Thank you again for bringing this to our attention.
