### ISSUE TITLE
Implementation issues

### ISSUE THREAD

**Issue by asifbanka** [graphchallenge/GraphChallenge#9]
Dear team,

I find this an extremely exciting project and look forward to contribute.

Being a novice I am facing issues at very early part of implementation. I have cloned the library and now I m stuck which direction to take.

Can you please redirect me to some reference manual that could be followed to take the implementation further.

**Comment by edward-kao** [comment]
Thank you for your interest! The full specifications of the challenges as well as instructions for submission are documented at our official website: http://graphchallenge.mit.edu/

For each challenge, the specification is given in our published papers and Powerpoint slides. Code (the repository you cloned) and data sets are all available as well (info on our website).
